language: scala
scala:
  - 2.11.7
before_install:
  - git clone --recursive https://github.com/dmlc/xgboost
  - cd xgboost/jvm-packages; mvn -q clean install -DskipTests; cd ../../
install:
  - sbt ++2.11.7 test