language: scala
scala:
  - 2.12.1

#before_install:
#  - git clone --recursive https://github.com/dmlc/xgboost
#  - cd xgboost/jvm-packages; mvn -q clean install -DskipTests -Dmaven.test.skip=true; cd ../../

install:
  gradle wrapper --gradle-version 5.6.2

script:
  #- travis_wait 30 ./gradlew clean test -PisCI=true --info
  - ./gradlew clean test -PisCI=true --info

cache:
  directories:
    - xgboost
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
#    - $HOME/.m2